- name: docker build and push
  hosts: all  # Replace with the hostname or IP address of your target server
 # become: yes  # Run tasks with sudo privileges

  tasks: 

    - name: Build Docker Image
      command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/Petshop

    - name: tag image
      command: docker tag petstore:latest niraniasandeep/petstore:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: niraniasandeep
        password: ${docker_pass}

    - name: Push image
      command: docker push niraniasandeep/petstore:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 niraniasandeep/petstore:latest
